### ISSUE TITLE
Colouring of output generated by the hook script is lost

### ISSUE THREAD

**Issue by oyeb** [qgadrian/elixir_git_hooks#1]
_BEGIN RANT_
First of all, I was overjoyed to find this! Thanks for doing this! :heart: 

I've tried putting verbose instructions (like in this [SO post](https://stackoverflow.com/questions/4592838/symbolic-link-to-a-hook-in-git#4594681)) in our CONTRIBUTING guide to set up our recommended gith-hooks -- but some people just ignore it and get very annoyed when the CI fails their PR because they pushed badly formatted code.

Hopefully, just doing `mix git_hooks.install` would make things easier :crossed_fingers: 
_END RANT_

--------
I like to run `credo` right after I commit, but I lose the beautifully colorized credo output when the hook runs via the mix task :slightly_frowning_face:

## Steps to reproduce
My relevant `config.exs`
```elixir
config :git_hooks,
  verbose: true,
  hooks: [
    pre_commit: [
      mix_tasks: [
        "format --check-formatted"
      ]
    ],
    post_commit: [
      mix_tasks: [
        "credo --strict"
      ]
    ]
  ]
```
## Expected result 
Something like this :rainbow: [(image)](https://i.imgur.com/Xysq2MU.png).
## But got this: [(image)](https://i.imgur.com/NzISPge.png)
No colors

**Comment by qgadrian** [comment]
Hi @oyeb, glad to hear you are enjoying this project!

I agree, it's better to have an automated git hook, people usually just ignore this best practices.

Remember that doing the gooks will be installed automatically after the dep is compiled, so even not doing `mix git_hooks.install` the hooks will be installed automatically.

I'll take a look so the output color of the tasks wont be overrided.

**Comment by oyeb** [comment]
> Remember that doing the gooks will be installed automatically after the dep is compiled, so even not doing mix git_hooks.install the hooks will be installed automatically.

Oh, that's neat! How is that implemented? Is it due to [this line](https://github.com/qgadrian/elixir_git_hooks/blob/master/lib/git_hooks.ex#L5)?

**Comment by qgadrian** [comment]
> Oh, that's neat! How is that implemented? Is it due to this line?

Exactly 👍

**Comment by qgadrian** [comment]
I wish this could be fixed sooner, but better late than never.

I added support to run [mix tasks](https://github.com/qgadrian/elixir_git_hooks#mix-task), and they will provide the same user feedback (thinking of terminal colors) as running then manually 🎉 

For reference, see the module documentation: https://github.com/qgadrian/elixir_git_hooks/blob/master/lib/tasks/mix.ex
