### ISSUE TITLE
0.6.5 release

### ISSUE THREAD

**Issue by chungwong** [qgadrian/elixir_git_hooks#110]
Is there a plan to release 0.6.5 soon?
I am just waiting for https://github.com/qgadrian/elixir_git_hooks/commit/ae998f3a7584161a46663859435adfcc21c521e8 to be included in the next release.

**Comment by qgadrian** [comment]
There you go!

https://github.com/qgadrian/elixir_git_hooks/releases/tag/v0.6.5

**Comment by qgadrian** [comment]
(published also on hex.pm)
