### ISSUE TITLE
mono-repo with multiple applications

### ISSUE THREAD

**Issue by jgallinari** [qgadrian/elixir_git_hooks#114]
Hello,

I'm using a mono-repo with multiple applications in their sub-directory, like
```bash
repo
└─ .git
└─ app1
   └─ .git
└─ app2
   └─ .git
```
So far, I had installed git_hooks v0.6.5 in the app sub-directories for some pre_commit hook defined for ex. in `repo/app1/config/config.exs` like
```elixir
if Mix.env() != :prod do
  config :git_hooks,
    auto_install: true,
    verbose: true,
    hooks: [
      pre_commit: [
        tasks: [
          {:cmd, "mix credo"},
...
```
 but it never worked for me: hooks never got fired automatically.
Then I saw [#96](https://github.com/qgadrian/elixir_git_hooks/issues/96).
So I removed `repo/app1/.git/hooks/` and I updated to git_hooks v0.7.1
Before that, I had only `.samples` in `repo/.git/hooks/`.
After the update, a new pre-commit file appeared in `repo/.git/hooks` that showed
```bash
#!/bin/sh
[ "/Users/jerome/repo/app1/deps/git_hooks" != "" ] && cd /Users/jerome/repo/app1/deps/git_hooks

mix git_hooks.run pre_commit "$@"
[ $? -ne 0 ] && exit 1
exit 0
```

So, it seems to me that it shouldn't work if I would do it also in `app2/`, doesn't it?

Then I tried anyway to commit a file  in `app1/` with some credo issue I introduced, which produced
```bash
repo> cd app1
app1> git commit -m 'test pre-commit hook' lib/app1/worker.ex
Unchecked dependencies for environment dev:
* blankable (Hex package)
  the dependency is not available, run "mix deps.get"
* ex_doc (Hex package)
  the dependency is not available, run "mix deps.get"
* recase (Hex package)
  the dependency is not available, run "mix deps.get"
* dialyxir (Hex package)
  the dependency is not available, run "mix deps.get"
* credo (Hex package)
  the dependency is not available, run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies
```
So maybe I did something wrong, but I can't get it to work in my case.
If, just for testing, I change `pre-commit` to be
```bash
#!/bin/sh
#[ "/Users/jerome/repo/app1/deps/git_hooks" != "" ] && cd /Users/jerome/repo/app1/deps/git_hooks
cd /Users/jerome/repo/app1
...
```
Then the same test would work
```bash
repo> cd app1
app1> git commit -m 'test pre-commit hook' lib/app1/worker.ex
↗ Running hooks for :pre_commit
...
× `pre_commit`: `mix credo` execution failed
```
 
Any thought about that? 🙂

**Comment by qgadrian** [comment]
Hello @jgallinari! Thanks for reporting the issue!

I believe this is the same issue as https://github.com/qgadrian/elixir_git_hooks/issues/113 correct? If that is the case, I opened a PR to validate adding a config to set up the project would work https://github.com/qgadrian/elixir_git_hooks/pull/120

In that case, if this library it's available on both of your projects it should work for both of them.

**Comment by jgallinari** [comment]
Hello,
Not sure to understand how it's supposed to work 😞
In `repo/app1/config/config.exs`, I put:
```elixir
if Mix.env() != :prod do
  config :git_hooks,
    project_path: "./app1",
    auto_install: true,
    verbose: true,
    hooks: [
      pre_commit: [
        tasks: [
          {:cmd, "mix credo"},
```
And then, by installing, I got
```bash
repo/app1> mix git_hooks.install
↗ Installing git hooks...
↗ Writing git hook for `pre_commit` to `../.git/hooks/pre-commit`
↗ Backing up git hook file `../.git/hooks/pre-commit` to `../.git/hooks/pre-commit.pre_git_hooks_backup`
↗ Writing git hook for `pre_push` to `../.git/hooks/pre-push`
↗ Backing up git hook file `../.git/hooks/pre-push` to `../.git/hooks/pre-push.pre_git_hooks_backup`
```
and `repo/.git/hooks/pre-commit` now contains:
```bash
#!/bin/sh

[ "./app1" != "" ] && cd "./app1"

mix git_hooks.run pre_commit "$@"
[ $? -ne 0 ] && exit 1
exit 0
```
which works.
But what am I supposed to do with `repo/app2` then?
I don't see how `repo/app1` and `repo/app2` can co-exist with a common config in `repo/.git/hooks/pre-commit`, can't they?

**Comment by qgadrian** [comment]
> Hello, Not sure to understand how it's supposed to work 😞 In `repo/app1/config/config.exs`, I put:
> 
> ```elixir
> if Mix.env() != :prod do
>   config :git_hooks,
>     project_path: "./app1",
>     auto_install: true,
>     verbose: true,
>     hooks: [
>       pre_commit: [
>         tasks: [
>           {:cmd, "mix credo"},
> ```
> 
> And then, by installing, I got
> 
> ```shell
> repo/app1> mix git_hooks.install
> ↗ Installing git hooks...
> ↗ Writing git hook for `pre_commit` to `../.git/hooks/pre-commit`
> ↗ Backing up git hook file `../.git/hooks/pre-commit` to `../.git/hooks/pre-commit.pre_git_hooks_backup`
> ↗ Writing git hook for `pre_push` to `../.git/hooks/pre-push`
> ↗ Backing up git hook file `../.git/hooks/pre-push` to `../.git/hooks/pre-push.pre_git_hooks_backup`
> ```
> 
> and `repo/.git/hooks/pre-commit` now contains:
> 
> ```shell
> #!/bin/sh
> 
> [ "./app1" != "" ] && cd "./app1"
> 
> mix git_hooks.run pre_commit "$@"
> [ $? -ne 0 ] && exit 1
> exit 0
> ```
> 
> which works. But what am I supposed to do with `repo/app2` then? I don't see how `repo/app1` and `repo/app2` can co-exist with a common config in `repo/.git/hooks/pre-commit`, can't they?

If it's an umbrella application, if both applications use this library you can have this library configured at the root config file instead of on each application.

If it's not an umbrella application I can try to dig more to support your case ☺️. It would be very helpful to speed up things if you can provide an example project to reproduce the issue.

**Comment by jgallinari** [comment]
Sorry for the delay of my response.
I could not get it to work until I re-installed the git_hooks manually with `mix git_hooks.install`, and suddenly it started to work as expected 😮 : .git/hooks/pre-commit got the right cd command.
Thanks for your help!
I think you can close the ticket.

**Comment by qgadrian** [comment]
@jgallinari glad to hear. If you have any issues please free to ping me here or open a new ticket ☺️
