### ISSUE TITLE
git_hooks.run not found

### ISSUE THREAD

**Issue by paridin** [qgadrian/elixir_git_hooks#116]
After the update to 0.7.0, we received the message `git_hooks.run not found`, which will be related to the [project path](https://github.com/qgadrian/elixir_git_hooks/blob/19b7970b61d3282f2fdd86c434f6afd800780489/priv/hook_template#L3). It won't support spaces around the route.

I'm open to doing a PR

suggested change for the cd.
```sh
[ "$project_path" != "" ] && cd "$project_path"
```

**Comment by qgadrian** [comment]
Thanks @paridin, good one! I will release a quick fix for this
