### ISSUE TITLE
mix compile --warnings-as-errors succeeds, but git_hooks registers as a failure

### ISSUE THREAD

**Issue by rt-chang** [qgadrian/elixir_git_hooks#118]
Hey there,

We noticed that after upgrading from 0.6.4 --> 0.7.0+, one of the steps in our pre-push pipeline was breaking. This was due to `mix compile --warnings-as-errors` returning `{:noop, []}` and that isn't one of the "successes" [here](https://github.com/qgadrian/elixir_git_hooks/blob/77b81f6caa77ec0a3d051051c46b0d1752a40447/lib/tasks/mix.ex#L80). Unsure if there is more complexity other than adding the result there? Happy to open a PR, if so lemme know

As a workaround, we've changed our config from...
```
config :git_hooks,
  hooks: [
    pre_push: [
      tasks: [
        {:mix_task, :compile, ["--warnings-as-errors"]}
      ]
    ]
  ]
```

to this, for the time being...
```
config :git_hooks,
  hooks: [
    pre_push: [
      tasks: [
        {:cmd, "mix compile --warnings-as-errors"}
      ]
    ]
  ]
```

Exact error wording: 
```
× mix task `compile` failed, return result: {:noop, []}
```

**Comment by qgadrian** [comment]
@rt-chang thanks for the report! I added a new config `extra_sucess_returns` so you can setup custom return values from your mix tasks. Will be available in the next release.

I decided this library to not support by default `{:noop, []}` to be more transparent in the project configuration :/

**Comment by rt-chang** [comment]
@qgadrian looks good, I noticed a few typos on the spelling of `success`. I did attempt to open a PR myself, but I don't think I have the right permissions

linking to line of code below:
- https://github.com/qgadrian/elixir_git_hooks/blob/master/README.md?plain=1#L213
- https://github.com/qgadrian/elixir_git_hooks/blob/master/lib/config.ex#L72-L74
- https://github.com/qgadrian/elixir_git_hooks/blob/master/lib/tasks/mix.ex#L64  (`@success_results` and `extra_success_results()`
- https://github.com/qgadrian/elixir_git_hooks/blob/master/lib/tasks/mix.ex#L85 (`@success_results`)
- https://github.com/qgadrian/elixir_git_hooks/blob/master/lib/tasks/mix.ex#L90
-

**Comment by qgadrian** [comment]
feature released in https://github.com/qgadrian/elixir_git_hooks/releases/tag/v0.7.3
