### ISSUE TITLE
only flag of mix dependencies doesnt work

### ISSUE THREAD

**Issue by msudgh** [qgadrian/elixir_git_hooks#26]
I did add git_hooks configs to the `config.exs` file and set `only` flag for [:dev, :test] to be used but in case of PROD environment, i see the following logs.

```bash
You have configured application :git_hooks in your configuration file,
but the application is not available.

This usually means one of:

1. You have not added the application as a dependency in a mix.exs file.

2. You are configuring an application that does not really exist.

Please ensure :git_hooks exists or remove the configuration.
```

**Comment by qgadrian** [comment]
Hey @msudgh 

I updated the example configuration README to make it align with the dep configuration. Basically you need to add the profile condition to the `config.exs` to avoid using it when running the `prod` mode.
