### ISSUE TITLE
Add `auto install` option

### ISSUE THREAD

**Issue by qgadrian** [qgadrian/elixir_git_hooks#38]
Add `auto install` option to allow having the git hooks configuration and leveraing on developers if they want to install or not.

**Comment by akoutmos** [comment]
Howdy! Has any work been done on this front? If not I can take it on and take an initial stab at it. Some people on the team like their git hooks, other people don't, so we're looking to make this an opt-in.

Thanks!!

**Comment by qgadrian** [comment]
Hey @akoutmos 

I have some changes on stand by regarding this, I will give it a push to this ticket during this weekend.

**Comment by akoutmos** [comment]
Perfect :+1:. Thanks!

**Comment by akoutmos** [comment]
Thank you so much @qgadrian!! Looking forward to the next release to start using this :)

**Comment by akoutmos** [comment]
Howdy @qgadrian. Any chance you could cut a release with this functionality added in? Thanks :)!

**Comment by qgadrian** [comment]
Hey @akoutmos I just publish the `v0.4.2` version

**Comment by akoutmos** [comment]
Thanks a million! You rock :)
