### ISSUE TITLE
Cut a new release with updated dependencies

### ISSUE THREAD

**Issue by lobo-tuerto** [qgadrian/elixir_git_hooks#68]
Hello!

I've seen that your deps have been recently updated by **dependabot**.
Do you think you could try cutting a new release with the updated dependencies?

I'm trying to use `recase` 0.7.0 but cannot because of the hard dependency `git_hooks` has on 0.6.0. :(

Maybe soften the version requirement on minor version number? Along the lines of `{:recase, "~> 0.7"}`.

**Comment by qgadrian** [comment]
Hey @lobo-tuerto thanks for the reminder! I published [a new version](https://hex.pm/packages/git_hooks/0.5.2) with dependencies updated!

**Comment by lobo-tuerto** [comment]
Thanks you so much! :D
