### ISSUE TITLE
[Feature request] overriding the git hook so that we can make it run mix tasks inside of docker compose

### ISSUE THREAD

**Issue by oliverswitzer** [qgadrian/elixir_git_hooks#82]
My team uses docker compose to run our Phoenix app and try to execute all of our mix tasks within that context with 

`docker-compose exec mix <insert task here>`

(We do this to avoid having to set up the elixir/erlang ecosystem on every new dev machine)

It would be amazing if it were possible to override the default installed git hook to use `docker-compose exec mix <elixir git hooks task>` instead of `mix <elixir git hook task>` so we don't have to have mix on our local machine. I would add this functionality myself and open a PR, but I wasn't totally sure where I would do that... I know [`Mix.Tasks.GitHooks.Install`](https://github.com/qgadrian/elixir_git_hooks/blob/91db4a4acbf2069e9954eb9ce633541a28b808f4/lib/mix/tasks/git_hooks/install.ex) would likely have to be modified, but I don't know how we would thread a config value that might override `mix` to be `docker-compose exec mix...` to that install function.

Ideally, we could specify this some key in our config for git hooks that would tell `elixir_git_hooks` to install the git hook with a slightly different prefix than `mix`. Does this seem possible?

Thanks in advance!

**Comment by jeffometer** [comment]
+1 (ok, we're on the same team)

I see that the git hook template in priv needs to be changed, but my bash isn't good and I don't know how to change it there from a config in Elixir.

Also, we have a `./mix` exacutable file that wraps the docker-compose command and can be used the same way `mix` is used.  It might be easier to provide a "path to mix" that could work for people who don't have mix on their path and would also let us provide our `./mix` script.

Thanks.

**Comment by qgadrian** [comment]
@oliverswitzer @jeffometer guys could you please check https://github.com/qgadrian/elixir_git_hooks/pull/83 ?

I will take a deeper look later this weeking, but that should do it.

**Comment by jeffometer** [comment]
That seems to work perfectly, thank you thank you!

**Comment by qgadrian** [comment]
Awesome, I will make a couple of checks and submit a new release later today (UTC+2)

**Comment by jeffometer** [comment]
Just a note for me using a mix path of `docker-compose exec web mix` did not work (I got a TTY error), but this works `docker exec --tty $(docker-compose ps -q web) mix`.  You may want to put that in your documentation if you think it is relevant to include.

**Comment by qgadrian** [comment]
> Just a note for me using a mix path of `docker-compose exec web mix` did not work (I got a TTY error), but this works `docker exec --tty $(docker-compose ps -q web) mix`. You may want to put that in your documentation if you think it is relevant to include.

Absolutely, I think makes sense to add this kind of information to avoid anyone running into the same problems. Thanks for the hint!
