### ISSUE TITLE
Invalid hook path and script when using git_path

### ISSUE THREAD

**Issue by colinsmetz** [qgadrian/elixir_git_hooks#96]
Hello,

I have a git repository, where the Elixir project is inside a subfolder (let's say `./my_app/`) instead of being at the root of the git repo. The README suggests that we can use the `git_path` option in that case. So I have the following directory structure:

```
├─ .git/
└─ my_app/
   ├─ mix.exs
   ├─ config/
   │  └─ config.exs
   └─ ...
```

and the following config:

```elixir
  config :git_hooks,
    git_path: "../.git",
    auto_install: true,
    verbose: true,
    hooks: [
      pre_commit: [
        tasks: [
          {:cmd, "mix format --check-formatted"}
        ]
      ]
    ]
```

When I run `mix compile`, I see

```
==> git_hooks
Compiling 15 files (.ex)
↗ Installing git hooks...
```

But I see no hook in my `.git` directory. Instead, it seems to have used `my_app/deps/.git` as I have a `my_app/deps/.git/hooks/pre-commit` file in there.

When I install the hooks manually though, it works:

```
❯ mix git_hooks.install
↗ Installing git hooks...
↗ Writing git hook for `pre_commit` to `../.git/hooks/pre-commit`
↗ Backing up git hook file `../.git/hooks/pre-commit` to `../.git/hooks/pre-commit.pre_git_hooks_backup`
```

However, I get another problem after that: the hook script does not take into account the location of my project:

```sh
#!/bin/sh

# There should be a `cd /my_app` here
mix git_hooks.run pre_commit "$@"
[ $? -ne 0 ] && exit 1
exit 0
fi
```

If I try to commit I get:

```
** (Mix) The task "git_hooks.run" could not be found
Note no mix.exs was found in the current directory
```

Is there anyhting I'm doing wrong? How can I solve those issues?

**Comment by felipeloha** [comment]
+1

**Comment by felipeloha** [comment]
you can workaround this with the following configuration
`mix_path: "cd my_app && mix",`

**Comment by qgadrian** [comment]
It's been a while, but this got fixed 49ca50e56f4ada2d5ad4d7198cc2bfef2681894d

I just tested a submodule project and the hooks are installed under `.git/modules/my-other-project/hooks/`

@colinsmetz can you check the pre-release `v0.6.6-pre`?

**Comment by colinsmetz** [comment]
I don't use submodules, so I'm not sure my issue was clear.

I just tried again using the tag `v0.6.6-pre` and I mostly have the same behaviours :

* The git hook is installed in `my_app/deps/.git/pre-commit` when I do a `mix compile`
* If I run `mix git_hooks.install` it uses my `git_path`. There was a difference though. With the `git_path` set to `../.git` (as I did before), the pre-commit hook is created at `.git/pre-commit` instead of `.git/hooks/pre-commit`. I had to set it to `../git/hooks` now.
* The pre-commit script does not `cd` inside the folder with the Elixir project, so it fails

Note that I may have misunderstood the point of `git_path`. Is it limited to git submodules only?

**Comment by colinsmetz** [comment]
> you can workaround this with the following configuration
> mix_path: "cd my_app && mix",

Thanks, that solves my last point indeed.

**Comment by qgadrian** [comment]
> I don't use submodules, so I'm not sure my issue was clear.
> 
> I just tried again using the tag `v0.6.6-pre` and I mostly have the same behaviours :
> 
>     * The git hook is installed in `my_app/deps/.git/pre-commit` when I do a `mix compile`
> 
>     * If I run `mix git_hooks.install` it uses my `git_path`. There was a difference though. With the `git_path` set to `../.git` (as I did before), the pre-commit hook is created at `.git/pre-commit` instead of `.git/hooks/pre-commit`. I had to set it to `../git/hooks` now.
> 
>     * The pre-commit script does not `cd` inside the folder with the Elixir project, so it fails
> 
> 
> Note that I may have misunderstood the point of `git_path`. Is it limited to git submodules only?

`git_path` is not limited to submodules, actually, it should not be used on git submodules and this project supports them out of the box without any additional configuration.

I just tested an elixir project in a subfolder, and the following config installed the hooks on the correct parent path when running `mix deps.compile git_hooks`.

```elixir
  config :git_hooks,
    git_path: "../.git",
    auto_install: true,
    verbose: true,
    hooks: [
      pre_commit: [
        tasks: [
          {:mix_task, :format, ["--dry-run", "--check-formatted"]}
        ]
      ]
    ]
```

<img width="788" alt="image" src="https://user-images.githubusercontent.com/489004/152838382-5011043c-774e-4acf-8e12-7ce298260fad.png">

I don't link the `git_path` config, the name is misleading and the path should be resolved automatically. So thanks to the [changes on this PR](https://github.com/qgadrian/elixir_git_hooks/pull/106) you won't need to set any custom path, it will just work (hopefully). 

I just tested myself with both git submodules and a simple elixir subfolder (no submodule) and both the install and the hooks worked fine. There is a [pre-release](https://github.com/qgadrian/elixir_git_hooks/releases/tag/v0.7.0-pre) available on hex.

**Comment by qgadrian** [comment]
Closing this issue as it should be fixed in the [latest release](https://github.com/qgadrian/elixir_git_hooks/releases/tag/v0.7.0)
